### ISSUE TITLE
Split up main file

### ISSUE THREAD

**Issue by SebRut** [SebRut/pygrocy#110]
`grocy.py` is getting quite large and should be split up.

**Comment by yellalena** [comment]
is this still open?  can I work on it?

**Comment by SebRut** [comment]
Hey! This is indeed still open, altough without a lot of details unfortunately. Feel free to give it a try :)

**Comment by yellalena** [comment]
okay cool! :)

**Comment by yellalena** [comment]
hey could you please share the docker-compose file to run the tests. i can't find it in the repository.

**Comment by SebRut** [comment]
Hi, you can see the setup instructions for testing with docker [here](https://github.com/SebRut/pygrocy/blob/develop/.travis.yml#L14-L17) :)
