### ISSUE TITLE
Add path in request when creating base url

### ISSUE THREAD

**Issue by tikismoke** [SebRut/pygrocy#121]
If grocy in not host at the root of a web server but in an other directory every request failed due to the base_url not complete.
This is done in line https://github.com/SebRut/pygrocy/blob/8787acc6d4f5f16169894810e21ba09b0b4f831d/pygrocy/grocy_api_client.py#L294

In this case the port may be add behind a full path like http://grocy.localdomain/grocy/public/:80/api/stock
Wich can't be available.

**Comment by isabellaalstrom** [comment]
Maybe make port optional for these urls, should solve it?

**Comment by tikismoke** [comment]
> Maybe make port optional for these urls, should solve it?

Not sure it will use default port and place it at the same bad place in whole url.
For my point of view... It must be a path add as params so that the base_url will be complete like:
http://grocy.localdomain:80/grocy/public/api/stock

**Comment by tikismoke** [comment]
Something like this (not sure...)
```
class GrocyApiClient(object):
    def __init__(self, base_url, api_key, port: int = DEFAULT_PORT_NUMBER, path="", verify_ssl=True):
        self._base_url = '{}:{}:{}/api/'.format(base_url, port, path)
```

It will have to be optional (also in hass integration)

**Comment by jon-daemon** [comment]
I don't use HACS. I installed the grocy folder manually in custom_components but I can not connect on my external installation of grocy. The installation location is at https://mydomain/public/index.php
Is there any workaround?
