### ISSUE TITLE
With product location disabled nothing works

### ISSUE THREAD

**Issue by isabellaalstrom** [SebRut/pygrocy#129]
You can disable location tracking in the grocy addon with `stock_location_tracking: false`.
If that is configured I noticed pygrocy will not be able to handle a shopping list call with items without location in it. Location should perhaps be optional.

**Comment by noxhirsch** [comment]
I'm having the same problem!

**Comment by SebRut** [comment]
Do you have any stacktrace or error log available, maybe by increasing the log level?

**Comment by isabellaalstrom** [comment]
I get this: `Update of Shopping_list failed with 'NoneType' object has no attribute 'get'`
