### ISSUE TITLE
400 response when posting

### ISSUE THREAD

**Issue by isabellaalstrom** [SebRut/pygrocy#131]
This issue https://github.com/custom-components/grocy/issues/96 seems to have it's base in this line.
If I change to json instead of data, like this, it works:
`resp = requests.post(
            req_url, verify=self._verify_ssl, headers=self._headers, json=data
        )`
https://github.com/SebRut/pygrocy/blob/9514df441e55c4810dd158e23675b65f03f63428/pygrocy/grocy_api_client.py#L492

**Comment by isabellaalstrom** [comment]
Would that make something else not work, or is it changeable? I've tried all the service calls from ha with this change, and they all work with it.

**Comment by SebRut** [comment]
I have to check requests docs for this, will try to fix this this afternoon :)

**Comment by ludeeus** [comment]
The difference is the content-type header.
When you use `data` (even if you use `json.dups`for the payload) it uses `application/x-www-form-urlencoded` and stringify the payload
When you use `json` you do not need to dump the data, and it uses `application/json` and send it as json

**Comment by isabellaalstrom** [comment]
As soon as this is fixed I can maybe release the rewritten component :)
