### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by isabellaalstrom** [SebRut/pygrocy#133]
In ha with the component I only get these error messages, no matter what the reason for the 400 is.
``` 
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.1.78:9192/api/objects/tasks
```

Grocy is however also sending an error_message, like this:
``` 
"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: tasks.name\"}"

It would be awesome to get these in the error message from the lib too.
```

**Comment by isabellaalstrom** [comment]
I would like to open this again :)

**Comment by SebRut** [comment]
@isabellaalstrom this should be enough to get the error_message from the response body, anything else that would help with errors?

**Comment by isabellaalstrom** [comment]
I'm sure it's fine, I can try to get it to send an error to be sure
