### ISSUE TITLE
Missing generic put and get option

### ISSUE THREAD

**Issue by horphi0815** [SebRut/pygrocy#155]
Hi,

is there a way to modify location objects after adding with add_generic?

Best regads,

Phil

**Comment by SebRut** [comment]
Currently not, but sounds reasonable. Thank you for bringing this up, I'll look into implementing GET, PUT, DELETE for generics.

**Comment by horphi0815** [comment]
Great, thats perfect.
Your API linkage is really helpful!!!

Many thx,

Phil

**Comment by SebRut** [comment]
should be included in the next release!

**Comment by horphi0815** [comment]
Damned, how fast are you? ;-)

Many thx,

BR

Phil
