### ISSUE TITLE
[Error] Get Stock

### ISSUE THREAD

**Issue by horphi0815** [SebRut/pygrocy#203]
Traceback (most recent call last):

  File "D:/00_ServerDaten/NC_MRT/Pycharm/mrtarget/grocy.py", line 98, in grocyAddStock
    stock = grocy.stock()

  File "C:\Users\Server\PycharmProjects\venv\lib\site-packages\pygrocy\grocy.py", line 48, in stock
    raw_stock = self._api_client.get_stock()

  File "C:\Users\Server\PycharmProjects\venv\lib\site-packages\pygrocy\grocy_api_client.py", line 323, in get_stock
    return [CurrentStockResponse(**response) for response in parsed_json]

  File "C:\Users\Server\PycharmProjects\venv\lib\site-packages\pygrocy\grocy_api_client.py", line 323, in <listcomp>
    return [CurrentStockResponse(**response) for response in parsed_json]

  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CurrentStockResponse
**product -> location_id
  value is not a valid integer (type=type_error.integer)**

Need to be a String

Next ....

  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CurrentStockResponse
**product -> product_group_id
  value is not a valid integer (type=type_error.integer)**

class ProductData(BaseModel):
    id: int
    name: str
    description: Optional[str] = None
    location_id: **str** # changed from int to str
    product_group_id: Optional[**str**] = None # changed from int to str
    qu_id_stock: int
    qu_id_purchase: int
    qu_factor_purchase_to_stock: float
    picture_file_name: Optional[str] = None
    allow_partial_units_in_stock: Optional[bool] = False
    row_created_timestamp: datetime
    min_stock_amount: Optional[int]
    default_best_before_days: int

**Comment by SebRut** [comment]
This is (probably) an error in grocy, I created an issue over there for that.

**Comment by geoffwright240** [comment]
I stumbled into this error while playing with a fresh install of grocy and setting up products without a 'Product Group' specified. As soon as all products where associated with a Product Group, the error was no longer triggered. Can @horphi0815 verify that this is triggering the error on his end? (Sounds like he is first hitting the problem with a location_id, which I suspect is also empty in his setup.)

My (superficial) reading of Pydantic is that it is set up correctly with:

product_group_id: Optional[int] = None

I am not convinced that changing int to str is the correct fix, and I am not convinced that this is a grocy issue...although I am speculating at this stage. Should grocy force a product_group_id for each product? Currently, it allows the user to leave this empty. Empty seems like a reasonable option for the user but perhaps a default of int '0' is appropriate as a catch-all. So, grocy could fix this issue by imposing stricter rules around setting up a product but....

We should be able to handle the empty use case here with pygrocy.
