### ISSUE TITLE
min_stock_amount should be float, not int

### ISSUE THREAD

**Issue by karwosts** [SebRut/pygrocy#217]
Grocy allows min_stock_amount a value of up to 4 decimal places. 

The ProductData class assumes this will be an int:
```
 min_stock_amount: Optional[int]
```

Can this be changed to a float? I have number of products with min stock of 1/4 of a bottle, etc, so I get validation errors processing my stock via HA custom integration.

**Comment by SebRut** [comment]
Of course! Would you feel comfortable to create a little PR to change this?
