### ISSUE TITLE
Change base url and add port

### ISSUE THREAD

**Issue by BlueBlueBlob** [SebRut/pygrocy#32]
Hi.

What do you think about changing base url like : https://{HOST}:{PORT}
removing /api/ (I saw some confusion from users)
(Default port for Grocy is 9192, can optional)

Regards :)

**Comment by SebRut** [comment]
Sounds fine to me. Feel free to work and this and just explictly assign me to review that PR. If done right we should just have to change the initialization of `setUp` to fix failing tests in `test_grocy.py`.
