### ISSUE TITLE
Consider release to comply with semver

### ISSUE THREAD

**Issue by SebRut** [SebRut/pygrocy#33]
According to semver spec (https://semver.org) APIs should be in 1.0.0 when used publicly which is kinda the case with the grocy custom component.

**Comment by BlueBlueBlob** [comment]
It's about version ?
Travis said I have to tag a commit to bump version.
It's about it ?

**Comment by SebRut** [comment]
Sem(antic) Ver(sioning) is about using meaningful versions to indicate compatible releases. Currently we're on 0.x.x which means anything can break without notice but starting with version 1.0.0 all releases within the same major version have to be compatible. So this is mostly about making the library easier to use and update without having to do detailed checks on every new release :)

The thing with travis is about something different. We use travis to build and release new versions on PyPI for pip etc. To do so one has to increase the version in `setup.py` and tag the commit with `v` and the current version, e.g. `v0.12.0` for our next release. Currently I'm doing new releases every now and then as needed.

**Comment by BlueBlueBlob** [comment]
I'm learning a lot :)
Thanks.

**Comment by SebRut** [comment]
not real issue I guess
