### ISSUE TITLE
test API compliance using real grocy instance

### ISSUE THREAD

**Issue by SebRut** [SebRut/pygrocy#34]
- latest version,specific version???
- docker

**Comment by BlueBlueBlob** [comment]
Nice idea.
I was thinking about checking version.
For docker stuff... I need to learn about it :)

**Comment by BlueBlueBlob** [comment]
Happy new year, best wishes and the best for 2020 :)

Reading Grocy readme : 
https://github.com/grocy/grocy#demo-mode
To run Grocy like the demo website (with some dates)
And https://github.com/grocy/grocy-docker
To run Grocy in a docker.
My question : can we setup Travis with all this ?

**Comment by BlueBlueBlob** [comment]
:)
https://docs.travis-ci.com/user/docker/

Keep in touch

**Comment by SebRut** [comment]
Happy new year for you too :) I don't have that much time to try out stuff, but travis should run for all PRs so feel free to try stuff :)

**Comment by BlueBlueBlob** [comment]
Don't worry, I'm testing :).
It was for your information :)

**Comment by BlueBlueBlob** [comment]
Done :)
Just need to wait a Grocy release, to enable demo mode trough environment variable.
I will do a PR at Grocy release.

Best regards
