### ISSUE TITLE
Feature request : list all products in db not only in stock

### ISSUE THREAD

**Issue by BlueBlueBlob** [SebRut/pygrocy#59]
Hi

This request https://demo.grocy.info/api/objects/products is different from https://demo.grocy.info/api/stock.

It can be useful in case to update a product informations.

Great regards

**Comment by smhgit** [comment]
In general, it will be great to have support for get api/objects, supporting all object types.

**Comment by BlueBlueBlob** [comment]
Hey !

I'm cooking a lib just for data management.
https://github.com/BlueBlueBlob/pygrocydm

:)
