### ISSUE TITLE
Change id property names to "id" instread of "something_id"

### ISSUE THREAD

**Issue by markusressel** [SebRut/pygrocy#66]
Hey there, great library!

I'm using your library to build a [telegram bot to interact with grocy](https://github.com/markusressel/grocy-telegram-bot). So far it works great! :+1: 
However, when dealing with entities of different types it is cumbersome that they all have different names for their `id` property. Would it be possible to rename all those properties (`product_id`, `chore_id` etc.) to just `id`? Is the grocy API giving the info out this way or did you choose to do this for some reason?

Thx

**Comment by SebRut** [comment]
Tank you for enjoying or library! I guess currently we're simply using the naming provided by the API but I think normalizing the ids in the data layer (classes from grocy.py) to conform to `id` makes sense.
