### ISSUE TITLE
Return values inconsistent between API call methods

### ISSUE THREAD

**Issue by markusressel** [SebRut/pygrocy#70]
When implementing stuff in grocy-telegram-bot using the `remove_product_in_shopping_list()` and `add_product()` methods of pygrocy I stumbled over the fact that the first does return the HTTP response but the latter does not. This is a problem, especially since you do not use the `response.raise_for_status()` method, because errors happening on the API side will just get lost, even if the developer was cautious enough to check the method result.

I don't know if you have a plan on how to deal with this going forward, but imho pygrocy should never return any HTTP related data back to the developer using the library since that would negate the whole point of an abstraction layer.

In a different project I was involved with we always used the `raise_for_status()` method. Imho a little restructuring would greatly benefit the readability and simplicity of the API call related methods. Have a look at the `_do_request` method [here](https://github.com/femueller/python-n26/blob/a28b124f175e2dec62e8106a16213ad76e6d8c22/n26/api.py#L269) which allowed us to turn all of the API call methods into one-liners.

PS: I know you are currently busy, so I don't expect you to do anything. A little heads up would be great though :crossed_fingers:

**Comment by SebRut** [comment]
Moin Markus,
thank you for providing input to this library :)

> When implementing stuff in grocy-telegram-bot using the remove_product_in_shopping_list() and add_product() methods of pygrocy I stumbled over the fact that the first does return the HTTP response but the latter does not. 

Thank you for bringing this up, I guess it slipped through while checking the PR

> This is a problem, especially since you do not use the response.raise_for_status() method, because errors happening on the API side will just get lost, even if the developer was cautious enough to check the method result.

That's something I thought about, but I guess it got lost while implementing stuff.

> Imho a little restructuring would greatly benefit the readability and simplicity of the API call related methods. Have a look at the _do_request method here which allowed us to turn all of the API call methods into one-liners.

Again something that got lost while implementing stuff ^^

> PS: I know you are currently busy, so I don't expect you to do anything. A little heads up would be great though 🤞

I guess I won't implement anything from above list till april/may but feel free to start working on this and submit a PR, I'll probably be able to review it.

**Comment by BlueBlueBlob** [comment]
Something like this ? ;) https://github.com/BlueBlueBlob/pygrocydm/blob/master/pygrocydm/grocy_api_client.py

**Comment by markusressel** [comment]
> Something like this ? ;) https://github.com/BlueBlueBlob/pygrocydm/blob/master/pygrocydm/grocy_api_client.py

Yeah, similar to that.
Is this a fork of pygrocy or a lib you built on your own?

**Comment by BlueBlueBlob** [comment]
It's no

**Comment by BlueBlueBlob** [comment]
> > Something like this ? ;) https://github.com/BlueBlueBlob/pygrocydm/blob/master/pygrocydm/grocy_api_client.py
> 
> Yeah, similar to that.
> Is this a fork of pygrocy or a lib you built on your own?

No, it's not a fork because it handles generic entities only. But I will do a PR in this mind. If I can handle git branches ;)

Btw thank you for linking nice best practices 👍

Best regards

**Comment by BlueBlueBlob** [comment]
(sorry fr

**Comment by markusressel** [comment]
Does it solve the same problem? Might be a good idea to combine efforts, or use your lib as a dependency of pygrocy?

**Comment by BlueBlueBlob** [comment]
> Does it solve the same problem? Might be a good idea to combine efforts, or use your lib as a dependency of pygrocy?

No. Because pygrocy  doesn't handle entity.
But sure, we can combine all of this.

But first, I will do a PR to have a more consistent API. Because like @SebRut said "we loose with adding features" (or kind of it 😂, sorry for my English.)

@SebRut : sorry you are very busy, but can you comment plz ?
