### ISSUE TITLE
Get product by Barcode

### ISSUE THREAD

**Issue by JuanGrados** [SebRut/pygrocy#85]
First of all, very cool project, it seems to make very straight forward to integrate grocy with other systems.

I would like to add/consume products by scanning their barcodes unfortunately I haven't found a way to retrieve the product_id by giving the barcode, is it that possible?

In the [grocy-pyscanner](https://github.com/grocy/grocy-pyscanner/blob/09e62fa8b39d14f304e71edd46fb5e1ab095cc52/barcode_reader.py#L94) they do it by a get request, so it is possible bu I haven't found how to do it in pygrocy. 
Thanks a lot!

**Comment by georgegebbett** [comment]
I can do this :)

**Comment by georgegebbett** [comment]
Hi @SebRut, I have opened #208 for your review :)
